version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=whatsapp_api
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT}
        depends_on:
            - postgres
        restart: unless-stopped
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        environment:
            - TOKEN=${TOKEN}
            - PORT=${PORT}
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/whatsapp_api?schema=public
            - WEBHOOK_ENABLED=${WEBHOOK_ENABLED}
            - WEBHOOK_URL=${WEBHOOK_URL}
            - WEBHOOK_BASE64=${WEBHOOK_BASE64}
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules/

volumes:
    db:
